### ISSUE TITLE
Publish a blog post that describes the recent changes made to the meta-yaml files.

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-sumstats-tools#26]
Please keep in mind the following tasks:

- [x] Prepare the content for the blog. Please see the details in this [file](https://docs.google.com/document/d/1Vil-hRdhYtRWfXdL3ep144p6ai_i_UiOMRawwvpqJ_w/edit).
- [x] Update the Meta YAML changes on [Github](https://github.com/EBISPOT/gwas-summary-statistics-standard): requires review and merging to the master branch.
- [x] Ensure that all YAML files are in the new format.

**Comment by ljwh2** [comment]
@karatugo to review

**Comment by jiyue1214** [comment]
- [x] Prepare the content for the blog. Please see the details in this file.
- [x] Update the Meta YAML changes on Github: requires review and merging to the master branch.
- [x] Ensure that all YAML files are in the new format

**Comment by karatugo** [comment]
Review done https://github.com/EBISPOT/gwas-summary-statistics-standard/pull/23

**Comment by ljwh2** [comment]
Blog post is good to go.

**Comment by jiyue1214** [comment]
The [blog](https://ebispot.github.io/gwas-blog/streamlining-GWAS-Summary-Statistics-Data-Interpretation-with-Improved-YAML-Metadata/) has already been posted. The table is not easy to read, Should we think about replacing the table using a picture?

**Comment by ljwh2** [comment]
Also some images are not found affecting all older blog posts e.g. https://ebispot.github.io/gwas-blog/gwas-ui-production-release-2023/

**Comment by ljwh2** [comment]
@ala-ebi please consult with @jiyue1214 about this
